### ISSUE TITLE
peer failed:  Error:md5hash has not come back yet

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#131]
Route-broadcaster broadcasting fails at peering after adding the peer key. 

```
[connector] 2016-12-15T02:50:30.322Z connector:app info connector ready (republic attitude)
[api] 2016-12-15T02:50:32.760Z socket INFO Connected wvCjBjU0Brd3oHGpAAAB
[connector] 2016-12-15T02:50:35.323Z connector:route-broadcaster warn broadcasting routes to peer.2o6al.sgd.PZxRkMEd6sXAvLhCwWlm83BdCyg4nF7ZHWmESfjLfkA failed:  Error: 38601ecf-e839-44d2-87ad-8d1278603ac1 has not come back yet
[connector]     at Promise.race.Promise (/home/winthan/ilp-kit/node_modules/ilp-plugin-virtual/src/model/rpc.js:98:34)
[connector]     at JsonRpc1.call (/home/winthan/ilp-kit/node_modules/ilp-plugin-virtual/src/model/rpc.js:97:7)
[connector]     at PluginVirtual._sendMessage (/home/winthan/ilp-kit/node_modules/ilp-plugin-virtual/src/lib/plugin.js:107:21)
[connector]     at next (native)
[connector]     at onFulfilled (/home/winthan/ilp-kit/node_modules/co/index.js:65:19)
[connector]     at /home/winthan/ilp-kit/node_modules/co/index.js:54:5
[connector]     at PluginVirtual.co (/home/winthan/ilp-kit/node_modules/co/index.js:50:10)
[connector]     at PluginVirtual.createPromise (/home/winthan/ilp-kit/node_modules/co/index.js:30:15)
[connector]     at RouteBroadcaster._broadcastToLedger (/home/winthan/ilp-kit/node_modules/ilp-connector/src/lib/route-broadcaster.js:86:68)
[connector]     at RouteBroadcaster.broadcast (/home/winthan/ilp-kit/node_modules/ilp-connector/src/lib/route-broadcaster.js:72:12)
[connector]     at RouteBroadcaster.start (/home/winthan/ilp-kit/node_modules/ilp-connector/src/lib/route-broadcaster.js:50:12)
[connector]     at next (native)
[connector]     at onFulfilled (/home/winthan/ilp-kit/node_modules/co/index.js:65:19)
[connector]     at process._tickCallback (internal/process/next_tick.js:103:7)

```
My dep version
```
├─┬ ilp@7.1.0
├─┬ ilp-connector@12.4.3
 ├─┬ ilp-kit-cli@9.0.1
├─┬ ilp-plugin-bells@9.2.1
├─┬ ilp-plugin-virtual@9.0.1 
├─┬ five-bells-ledger@19.3.0
├─┬ five-bells-condition@3.3.1
├─┬ five-bells-shared@14.1.2 
├─┬ UNMET PEER DEPENDENCY react@15.4.1 
npm ERR! peer dep missing: react@0.14.x, required by redux-async-connect@1.0.0-rc4
```

**Comment by sharafian** [comment]
That's Plugin Virtual's message when nobody responds to an RPC request. It will usually happen when you're the only one on a trustline (eg. you peered with someone but they didn't peer with you).

I'll change the message to make it clearer, because that's hard to guess from the error message.

**Comment by sharafian** [comment]
https://github.com/interledgerjs/ilp-plugin-virtual/commit/be3618d20cd4b2dd71e4a0c966d640d40af2a61c
