### ISSUE TITLE
 Error: Transfer expired, money returned 

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#141]
UI said "You've just sent some money!", but there are errors 

   -  InvalidBodyError: IlpAddress schema validation error
   -  Error: Transfer expired, money returned

```
[ledger] 2016-12-18T05:41:36.517Z ledger:koa info <-- PUT /transfers/eb513462-4626-4deb-8fb4-5f394c6c675d/rejection
[connector] 2016-12-18T05:41:36.625Z connector:subscriptions warn error processing notification: Error: request with id 79b71de8-1622-434c-8d31-2f86e80f8a40 has timed out. are you the only one on this trustline?
[ledger] 2016-12-18T05:41:36.627Z ledger:koa info --> PUT /transfers/eb513462-4626-4deb-8fb4-5f394c6c675d/rejection 201 110ms 136B
 [connector] 2016-12-18T05:41:36.638Z connector:subscriptions warn error processing notification: InvalidBodyError: IlpAddress schema validation error: should be string
[api] 2016-12-18T05:41:41.327Z error-handler ERROR { Error: Transfer expired, money returned
[api]     at Timeout.setTimeout (/home/winthan/usd/node_modules/ilp/src/lib/sender.js:177:20)
[api]     at ontimeout (timers.js:365:14)
: [api]     at tryOnTimeout (timers.js:237:5)
 [api]     at Timer.listOnTimeout (timers.js:207:5) headers: { 'Access-Control-Allow-Origin': '*' } }
 [api] 2016-12-18T05:41:41.333Z error-handler ERROR Error: Transfer expired, money returned
 [api]     at Timeout.setTimeout (/home/winthan/usd/node_modules/ilp/src/lib/sender.js:177:20)
[api]     at ontimeout (timers.js:365:14)
[api]     at tryOnTimeout (timers.js:237:5)
 [api]     at Timer.listOnTimeout (timers.js:207:5)
 [api] 2016-12-18T05:41:41.337Z http INFO   xxx PUT /payments/3d2b5a32-3d76-4121-844b-792be0b049b2 500 13s -
 [api]
 [api]   InternalServerError: Error: Transfer expired, money returned
[api]       at Object.throw (/home/winthan/usd/node_modules/koa.io/node_modules/koa/lib/context.js:90:23)
 [api]       at Object.handleError (/home/winthan/usd/node_modules/five-bells-shared/middlewares/error-handler.js:18:19)
 [api]       at throw (native)
[api]       at onRejected (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:77:24)

```

**Comment by vhpoet** [comment]
See https://github.com/interledgerjs/ilp-kit/issues/105

**Comment by Winthan** [comment]
Great, I subscribe that issue 105 for update.
