### ISSUE TITLE
possible EventEmitter memory leak 

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#146]
```
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
[api] Trace
[api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
[api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:58:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
[api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:60:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:62:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:64:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:66:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:58:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:60:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:62:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:64:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
 [api] Trace
 [api]     at FiveBellsLedger.EventEmitter.on (/home/winthan/usd/node_modules/ilp-plugin-bells/node_modules/eventemitter2/lib/eventemitter2.js:516:21)
 [api]     at Client (/home/winthan/usd/node_modules/ilp-core/src/lib/client.js:66:10)
 [api]     at Object.createReceiver (/home/winthan/usd/node_modules/ilp/src/lib/receiver.js:32:33)
 [api]     at SPSP.getReceiver (/home/winthan/usd/api/src/lib/spsp.js:170:28)
 [api]     at next (native)
 [api]     at onFulfilled (/home/winthan/usd/node_modules/koa.io/node_modules/co/index.js:61:19)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api]   ilp:receiver account: us.usd.usd.nyeinminn ledger info:  { connectors:
 [api]    [ { id: 'https://usd.interledger.network/ledger/accounts/usd',
 [api]        name: 'usd' } ],
 [api]   precision: 10,
 [api]   scale: 2,
 [api]   currencyCode: 'USD',
 [api]   currencySymbol: '$' } +41s
 [api]   ilp:receiver receiver listening +4ms
 [api]   ilp-kit:spsp created a receiver object +0ms
 [api]   ilp:receiver creating request with params: { amount: '9.72' } +1ms
 [api]   ilp:receiver created payment request: { address: 'us.usd.usd.nyeinminn.d602aae8-0508-40dc-a7ca-15b0c1f7aef0',
 [api]   amount: '9.72',
 [api]   expires_at: '2016-12-21T07:37:49.008Z',
 [api]   condition: 'cc:0:3:HAJoxEuahyWNuF-ZidLeZFxVFI0y2d1Jkgj31Hii2Z0:32' } +2ms

```

**Comment by peterjkrey** [comment]
Is this behavior still being observed? @Winthan
