### ISSUE TITLE
 SequelizeUniqueConstraintError: Validation error

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#147]
Profile Names cannot be changed in UI.  

```
[api] 2016-12-21T08:03:01.235Z sequelize DEBUG Executing (default): INSERT INTO "Users" ("id","username","account","name","created_at","updated_at") VALUES (1,'admin','http://wallet1.com/ledger/accounts/admin','USD - Interledger Network','2016-11-29 18:21:46.970 +00:00','2016-12-21 08:03:01.230 +00:00') RETURNING *;
[api] 2016-12-21T08:03:01.241Z users WARN { SequelizeUniqueConstraintError: Validation error
[api]     at Query.formatError (/home/winthan/usd/node_modules/sequelize/lib/dialects/postgres/query.js:326:16)
[api]     at Query.<anonymous> (/home/winthan/usd/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
[api]     at emitOne (events.js:96:13)
[api]     at Query.emit (events.js:188:7)
[api]     at Query.handleError (/home/winthan/usd/node_modules/pg/lib/query.js:108:8)
[api]     at Connection.<anonymous> (/home/winthan/usd/node_modules/pg/lib/client.js:171:26)
[api]     at emitOne (events.js:96:13)
[api]     at Connection.emit (events.js:188:7)
[api]     at Socket.<anonymous> (/home/winthan/usd/node_modules/pg/lib/connection.js:109:12)
[api]     at emitOne (events.js:96:13)
[api]     at Socket.emit (events.js:188:7)
[api]     at readableAddChunk (_stream_readable.js:176:18)
[api]     at Socket.Readable.push (_stream_readable.js:134:10)
[api]     at TCP.onread (net.js:548:20)
[api]   name: 'SequelizeUniqueConstraintError',
[api]   message: 'Validation error',
[api]   errors:
[api]    [ { message: 'id must be unique',
[api]        type: 'unique violation',
[api]        path: 'id',
[api]        value: '1' } ],
[api]   fields: { id: '1' },
[api]   parent:
[api]    { error: duplicate key value violates unique constraint "Users_pkey"
[api]        at Connection.parseE (/home/winthan/usd/node_modules/pg/lib/connection.js:539:11)
[api]        at Connection.parseMessage (/home/winthan/usd/node_modules/pg/lib/connection.js:366:17)
[api]        at Socket.<anonymous> (/home/winthan/usd/node_modules/pg/lib/connection.js:105:22)
[api]        at emitOne (events.js:96:13)
[api]        at Socket.emit (events.js:188:7)
[api]        at readableAddChunk (_stream_readable.js:176:18)
[api]        at Socket.Readable.push (_stream_readable.js:134:10)
[api]        at TCP.onread (net.js:548:20)
[api]      name: 'error',
[api]      length: 173,
[api]      severity: 'ERROR',
[api]      code: '23505',
[api]      detail: 'Key (id)=(1) already exists.',
[api]      hint: undefined,
[api]      position: undefined,
[api]      internalPosition: undefined,
[api]      internalQuery: undefined,
[api]      where: undefined,
[api]      schema: 'public',
[api]      table: 'Users',
[api]      column: undefined,
[api]      dataType: undefined,
[api]      constraint: 'Users_pkey',
[api]      file: 'nbtinsert.c',
[api]      line: '424',
[api]      routine: '_bt_check_unique',
[api]      sql: 'INSERT INTO "Users" ("id","username","account","name","created_at","updated_at") VALUES (1,\'admin\',\'http://wallet1.com/ledger/accounts/admin\',\'USD - Interledger Network\',\'2016-11-29 18:21:46.970 +00:00\',\'2016-12-21 08:03:01.230 +00:00\') RETURNING *;' },
[api]   original:
[api]    { error: duplicate key value violates unique constraint "Users_pkey"
[api]        at Connection.parseE (/home/winthan/usd/node_modules/pg/lib/connection.js:539:11)
[api]        at Connection.parseMessage (/home/winthan/usd/node_modules/pg/lib/connection.js:366:17)
[api]        at Socket.<anonymous> (/home/winthan/usd/node_modules/pg/lib/connection.js:105:22)
[api]        at emitOne (events.js:96:13)
[api]        at Socket.emit (events.js:188:7)
[api]        at readableAddChunk (_stream_readable.js:176:18)
[api]        at Socket.Readable.push (_stream_readable.js:134:10)
[api]        at TCP.onread (net.js:548:20)
[api]      name: 'error',
[api]      length: 173,
[api]      severity: 'ERROR',
[api]      code: '23505',
[api]      detail: 'Key (id)=(1) already exists.',
[api]      hint: undefined,
[api]      position: undefined,
[api]      internalPosition: undefined,
[api]      internalQuery: undefined,
[api]      where: undefined,
[api]      schema: 'public',
[api]      table: 'Users',
[api]      column: undefined,
[api]      dataType: undefined,
[api]      constraint: 'Users_pkey',
[api]      file: 'nbtinsert.c',
[api]      line: '424',
[api]      routine: '_bt_check_unique',
[api]      sql: 'INSERT INTO "Users" ("id","username","account","name","created_at","updated_at") VALUES (1,\'admin\',\'http://wallet1.com/ledger/accounts/admin\',\'USD - Interledger Network\',\'2016-11-29 18:21:46.970 +00:00\',\'2016-12-21 08:03:01.230 +00:00\') RETURNING *;' },
[api]   sql: 'INSERT INTO "Users" ("id","username","account","name","created_at","updated_at") VALUES (1,\'admin\',\'http://wallet1.com/ledger/accounts/admin\',\'USD - Interledger Network\',\'2016-11-29 18:21:46.970 +00:00\',\'2016-12-21 08:03:01.230 +00:00\') RETURNING *;' }
[api] 2016-12-21T08:03:01.252Z http INFO   --> PUT /users/admin 500 99ms -

```

**Comment by vhpoet** [comment]
@Winthan should be fixed by https://github.com/interledgerjs/ilp-kit/commit/fee50ebbd4194933e0d2ffbd026f36cf332092d9.
