### ISSUE TITLE
 API - links.map is not a function

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#160]
```
[api]  /node_modules/webfinger.js/src/webfinger.js:212
[api]     links.map(function (link, i) {
[api]           ^
[api]
[api] TypeError: links.map is not a function
[api]     at WebFinger.__processJRD ( /node_modules/webfinger.js/src/webfinger.js:212:11)
[api]     at  /node_modules/webfinger.js/src/webfinger.js:310:14
[api]     at __processState ( /node_modules/webfinger.js/src/webfinger.js:111:18)
[api]     at xhr.onreadystatechange ( /node_modules/webfinger.js/src/webfinger.js:148:11)
[api]     at dispatchEvent ( /node_modules/webfinger.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
[api]     at setState ( /node_modules/webfinger.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
[api]     at IncomingMessage.<anonymous> ( /node_modules/webfinger.js/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
[api]     at emitNone (events.js:91:20)
[api]     at IncomingMessage.emit (events.js:185:7)
[api]     at endReadableNT (_stream_readable.js:974:12)
[api]     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[api]     at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by vhpoet** [comment]
This exception is coming from the webfinger library, when is this happening?

**Comment by Winthan** [comment]
This is happening when I am trying to run with the latest git clone of ilp-kit. 

I don't see any update at web finger library, I have web finger 2.6.0.

**Comment by Winthan** [comment]
When you try to add peers in admin UI, it causes the same error as well.

**Comment by vhpoet** [comment]
This should already be fixed.
