### ISSUE TITLE
Connector fail

### ISSUE THREAD

**Issue by Winthan** [interledgerjs/ilp-kit#161]
I got no issue with old connector version. When I use with latest connector version  "version": "12.8.2". I am getting this issue at broadcasting. I have connector ledgers for trust lines in ENV.list as well as in admin UI. 

 ```
 [api]   ilp-kit:spsp created a sender object +37s
 [api]   ilp-core remote quote connector=us.usd.interledger.interledger query={"source_address":"us.usd.interledger.admin","source_amount":"1","destination_address":"mm.mmk.interledger.winthan"} +8ms
 [ledger] 2017-01-03T03:25:01.975Z ledger:koa info <-- POST /messages
 [ledger] 2017-01-03T03:25:02.001Z ledger:koa info --> POST /messages 201 26ms 383B
 [connector] notify message https://usd.interledger.network/ledger/accounts/admin
 [connector] 2017-01-03T03:25:02.008Z connector:route-builder info creating quote sourceAddress=us.usd.interledger.admin sourceAmount=1 destinationAddress=mm.mmk.interledger.winthan destinationAmount=undefined destinationPrecisionAndScale=undefined slippage=undefined
 [connector] searching best hop from us.usd.interledger.admin to mm.mmk.interledger.winthan for 1 (by src amount)
 [connector] destination mm.mmk.interledger.winthan is not in known destinations: peer.32oKK.mmk.
 [ledger] 2017-01-03T03:25:02.024Z ledger:koa info <-- POST /messages
 [ledger] 2017-01-03T03:25:02.035Z ledger:koa info --> POST /messages 201 10ms 353B
 [api]   ilp-plugin-bells:factory sending notification to https://usd.interledger.network/ledger/accounts/admin +92ms
 [api]   ilp-plugin-bells:plugin notify message https://usd.interledger.network/ledger/accounts/interledger +1ms
 [api]   ilp-core getQuote: ignoring remote quote error: This connector does not support the given asset pair +1ms
 [api]   ilp:sender got source amount quote response undefined +1ms
 [api] Error: Got empty quote response from the connector
 [api]     at client.connect.then.then.then (/home/winthan/usdnode/node_modules/ilp/src/lib/sender.js:55:17)
 [api]     at process._tickCallback (internal/process/next_tick.js:103:7)
 [api] 2017-01-03T03:25:02.044Z error-handler WARN Not Found: No quote for a specified destination/amount has been found
 [api] 2017-01-03T03:25:02.049Z http INFO   --> POST /payments/quote 404 2,272ms -
```

**Comment by sharafian** [comment]
Could you post your ILP Kit version as well as your CONNECTOR_LEDGERS field? You're right that the `not in known destinations` error is a broadcasting issue. Are you seeing any route broadcasts from `mm.mmk.interledger.`, or is `mm.mmk.interledger` not broadcasting routes at all?

**Comment by Winthan** [comment]
I am having

"name": "ilp-kit", "version": "1.0.0",
"ilp": "7.1.0",
"ilp-connector": "^12.8.2",
"ilp-kit-cli": "10.0.5",

mm.mmk.interledger seems broadcast though. But failed at route-broadcaster. 
 ```
[connector] 2017-01-03T15:06:01.289Z connector:app info pair [ 'MMK@mm.mmk.interledger.', 'USD@peer.32oKK.usd.' ]
 [connector] 2017-01-03T15:06:01.295Z connector:app info pair [ 'USD@peer.32oKK.usd.', 'MMK@mm.mmk.interledger.' ]
 [connector] connecting to account https://mmk.interledger.network/ledger/accounts/interledger
 [connector] undefined: connecting to host `mqtt://broker.hivemq.com:1883`...
 [ledger] 2017-01-03T15:06:02.788Z ledger:koa info <-- GET /accounts/interledger
 [ledger] 2017-01-03T15:06:02.810Z ledger:koa info --> GET /accounts/interledger 200 22ms 139B
 [connector] request ledger metadata https://mmk.interledger.network/ledger
 [ledger] 2017-01-03T15:06:02.823Z ledger:koa info <-- GET /
 [ledger] 2017-01-03T15:06:02.825Z ledger:koa info --> GET / 200 2ms 986B
 [connector] using service urls: { transfer: 'https://mmk.interledger.network/ledger/transfers/:id',
 [connector]   transfer_fulfillment: 'https://mmk.interledger.network/ledger/transfers/:id/fulfillment',
 [connector]   transfer_rejection: 'https://mmk.interledger.network/ledger/transfers/:id/rejection',
 [connector]   account: 'https://mmk.interledger.network/ledger/accounts/:name',
 [connector]   auth_token: 'https://mmk.interledger.network/ledger/auth_token',
 [connector]   websocket: 'wss://mmk.interledger.network/ledger/websocket',
 [connector]   message: 'https://mmk.interledger.network/ledger/messages' }
 [ledger] 2017-01-03T15:06:02.845Z ledger:koa info <-- GET /auth_token
 [ledger] 2017-01-03T15:06:02.880Z ledger:koa info --> GET /auth_token 200 35ms 293B
 [ledger] 2017-01-03T15:06:02.916Z ledger:koa info <-| GET /websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTU5NjIsImV4cCI6MTQ4NDA2MDc2MiwiaXNzIjoiaHR0cHM6Ly9tbWsuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL21tay5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9pbnRlcmxlZGdlciJ9.IFOMg_UgKtAhNXXBaDBFDUCuasfwaKKU_gFLktbAMo8
 [connector] ws connected to wss://mmk.interledger.network/ledger/websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTU5NjIsImV4cCI6MTQ4NDA2MDc2MiwiaXNzIjoiaHR0cHM6Ly9tbWsuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL21tay5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9pbnRlcmxlZGdlciJ9.IFOMg_UgKtAhNXXBaDBFDUCuasfwaKKU_gFLktbAMo8
 [ledger] 2017-01-03T15:06:02.962Z ledger:rpcHandler info new ws subscriber for interledger:*
 [connector] request ledger metadata https://mmk.interledger.network/ledger
 [connector] 2017-01-03T15:06:02.973Z connector:route-broadcaster info adding peer -VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM via ledger peer.32oKK.usd.
 [ledger] 2017-01-03T15:06:02.978Z ledger:koa info <-- GET /
 [ledger] 2017-01-03T15:06:02.980Z ledger:koa info --> GET / 200 2ms 986B
 [connector] 2017-01-03T15:06:02.995Z connector:route-broadcaster info broadcasting 1 routes to peer.32oKK.usd.-VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM
 [connector] 1 calling sendMessage with [ { ledger: 'peer.32oKK.usd.',
 [connector]     account: 'peer.32oKK.usd.9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0',
 [connector]     data: { method: 'broadcast_routes', data: [Object] } } ] and id 222935c4-04c6-49dd-8af1-af85f3f4450e
 [connector] 2017-01-03T15:06:03.007Z connector:app info connector ready (republic attitude)
 [api]   ilp-plugin-bells:factory connecting admin plugin +0ms
 [api]   ilp-plugin-bells:plugin connecting to account https://mmk.interledger.network/ledger/accounts/admin +5ms
 [ledger] 2017-01-03T15:06:04.386Z ledger:koa info <-- GET /accounts/admin
 [ledger] 2017-01-03T15:06:04.396Z ledger:koa info --> GET /accounts/admin 200 10ms 127B
 [api]   ilp-plugin-bells:plugin request ledger metadata https://mmk.interledger.network/ledger +52ms
 [ledger] 2017-01-03T15:06:04.408Z ledger:koa info <-- GET /
 [ledger] 2017-01-03T15:06:04.411Z ledger:koa info --> GET / 200 3ms 986B
 [api]   ilp-plugin-bells:plugin using service urls: { transfer: 'https://mmk.interledger.network/ledger/transfers/:id',
 [api]   transfer_fulfillment: 'https://mmk.interledger.network/ledger/transfers/:id/fulfillment',
 [api]   transfer_rejection: 'https://mmk.interledger.network/ledger/transfers/:id/rejection',
 [api]   account: 'https://mmk.interledger.network/ledger/accounts/:name',
 [api]   auth_token: 'https://mmk.interledger.network/ledger/auth_token',
 [api]   websocket: 'wss://mmk.interledger.network/ledger/websocket',
 [api]   message: 'https://mmk.interledger.network/ledger/messages' } +16ms
 [ledger] 2017-01-03T15:06:04.426Z ledger:koa info <-- GET /auth_token
 [ledger] 2017-01-03T15:06:04.444Z ledger:koa info --> GET /auth_token 200 18ms 285B
 [ledger] 2017-01-03T15:06:04.451Z ledger:koa info <-| GET /websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTU5NjQsImV4cCI6MTQ4NDA2MDc2NCwiaXNzIjoiaHR0cHM6Ly9tbWsuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL21tay5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9hZG1pbiJ9.BmhBePGQRZRMIVAdkdxmVH54h4-SQfiW8ahl9mJuAiA
 [api]   ilp-plugin-bells:plugin ws connected to wss://mmk.interledger.network/ledger/websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTU5NjQsImV4cCI6MTQ4NDA2MDc2NCwiaXNzIjoiaHR0cHM6Ly9tbWsuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL21tay5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9hZG1pbiJ9.BmhBePGQRZRMIVAdkdxmVH54h4-SQfiW8ahl9mJuAiA +45ms
 [ledger] 2017-01-03T15:06:04.476Z ledger:rpcHandler info new ws subscriber for admin:*
 [api]   ilp-plugin-bells:factory retrieving ledger metadata +21ms
 [api]   ilp-plugin-bells:plugin request ledger metadata https://mmk.interledger.network/ledger +2ms
 [ledger] 2017-01-03T15:06:04.488Z ledger:koa info <-- GET /
 [ledger] 2017-01-03T15:06:04.490Z ledger:koa info --> GET / 200 2ms 986B
 [connector] 2017-01-03T15:06:08.005Z connector:route-broadcaster warn broadcasting routes to peer.32oKK.usd.-VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM failed
```

Here is usd.interledger -

```
[connector] 2017-01-03T15:15:42.122Z connector:app info pair [ 'USD@us.usd.interledger.', 'MMK@peer.32oKK.mmk.' ]
[connector] 2017-01-03T15:15:42.131Z connector:app info pair [ 'MMK@peer.32oKK.mmk.', 'USD@us.usd.interledger.' ]
[connector] connecting to account https://usd.interledger.network/ledger/accounts/interledger
[connector] undefined: connecting to host `mqtt://broker.hivemq.com:1883`...
[ledger] 2017-01-03T15:15:42.338Z ledger:koa info <-- GET /accounts/interledger
[ledger] 2017-01-03T15:15:42.356Z ledger:koa info --> GET /accounts/interledger 200 18ms 139B
[connector] request ledger metadata https://usd.interledger.network/ledger
[ledger] 2017-01-03T15:15:42.406Z ledger:koa info <-- GET /
[ledger] 2017-01-03T15:15:42.407Z ledger:koa info --> GET / 200 1ms 984B
[connector] using service urls: { transfer: 'https://usd.interledger.network/ledger/transfers/:id',
[connector]   transfer_fulfillment: 'https://usd.interledger.network/ledger/transfers/:id/fulfillment',
[connector]   transfer_rejection: 'https://usd.interledger.network/ledger/transfers/:id/rejection',
[connector]   account: 'https://usd.interledger.network/ledger/accounts/:name',
[connector]   auth_token: 'https://usd.interledger.network/ledger/auth_token',
[connector]   websocket: 'wss://usd.interledger.network/ledger/websocket',
[connector]   message: 'https://usd.interledger.network/ledger/messages' }
[ledger] 2017-01-03T15:15:42.459Z ledger:koa info <-- GET /auth_token
[ledger] 2017-01-03T15:15:42.488Z ledger:koa info --> GET /auth_token 200 29ms 293B
[connector] ws connected to wss://usd.interledger.network/ledger/websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTY1NDIsImV4cCI6MTQ4NDA2MTM0MiwiaXNzIjoiaHR0cHM6Ly91c2QuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL3VzZC5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9pbnRlcmxlZGdlciJ9.s0XO6rNr22XjFQZrMPcyl2yB4eSfXH_ESK5_osrEBCg
[ledger] 2017-01-03T15:15:42.538Z ledger:koa info <-| GET /websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTY1NDIsImV4cCI6MTQ4NDA2MTM0MiwiaXNzIjoiaHR0cHM6Ly91c2QuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL3VzZC5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9pbnRlcmxlZGdlciJ9.s0XO6rNr22XjFQZrMPcyl2yB4eSfXH_ESK5_osrEBCg
[ledger] 2017-01-03T15:15:42.593Z ledger:rpcHandler info new ws subscriber for interledger:*
[connector] request ledger metadata https://usd.interledger.network/ledger
[connector] 2017-01-03T15:15:42.605Z connector:route-broadcaster info adding peer 9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0 via ledger peer.32oKK.mmk.
[ledger] 2017-01-03T15:15:42.614Z ledger:koa info <-- GET /
[ledger] 2017-01-03T15:15:42.617Z ledger:koa info --> GET / 200 3ms 984B
[connector] 2017-01-03T15:15:42.634Z connector:route-broadcaster info broadcasting 1 routes to peer.32oKK.mmk.9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0
[connector] 1 calling sendMessage with [ { ledger: 'peer.32oKK.mmk.',
[connector]     account: 'peer.32oKK.mmk.-VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM',
[connector]     data: { method: 'broadcast_routes', data: [Object] } } ] and id ded4edd1-f416-41ff-85a3-6d6c73fb0c8a
[connector] 20 [connector] 2017-01-03T15:15:42.122Z connector:app info pair [ 'USD@us.usd.interledger.', 'MMK@peer.32oKK.mmk.' ]
 [connector] 2017-01-03T15:15:42.131Z connector:app info pair [ 'MMK@peer.32oKK.mmk.', 'USD@us.usd.interledger.' ]
 [connector] connecting to account https://usd.interledger.network/ledger/accounts/interledger
 [connector] undefined: connecting to host `mqtt://broker.hivemq.com:1883`...
 [ledger] 2017-01-03T15:15:42.338Z ledger:koa info <-- GET /accounts/interledger
 [ledger] 2017-01-03T15:15:42.356Z ledger:koa info --> GET /accounts/interledger 200 18ms 139B
 [connector] request ledger metadata https://usd.interledger.network/ledger
 [ledger] 2017-01-03T15:15:42.406Z ledger:koa info <-- GET /
 [ledger] 2017-01-03T15:15:42.407Z ledger:koa info --> GET / 200 1ms 984B
 [connector] using service urls: { transfer: 'https://usd.interledger.network/ledger/transfers/:id',
 [connector]   transfer_fulfillment: 'https://usd.interledger.network/ledger/transfers/:id/fulfillment',
 [connector]   transfer_rejection: 'https://usd.interledger.network/ledger/transfers/:id/rejection',
 [connector]   account: 'https://usd.interledger.network/ledger/accounts/:name',
 [connector]   auth_token: 'https://usd.interledger.network/ledger/auth_token',
 [connector]   websocket: 'wss://usd.interledger.network/ledger/websocket',
 [connector]   message: 'https://usd.interledger.network/ledger/messages' }
 [ledger] 2017-01-03T15:15:42.459Z ledger:koa info <-- GET /auth_token
 [ledger] 2017-01-03T15:15:42.488Z ledger:koa info --> GET /auth_token 200 29ms 293B
 [connector] ws connected to wss://usd.interledger.network/ledger/websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTY1NDIsImV4cCI6MTQ4NDA2MTM0MiwiaXNzIjoiaHR0cHM6Ly91c2QuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL3VzZC5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9pbnRlcmxlZGdlciJ9.s0XO6rNr22XjFQZrMPcyl2yB4eSfXH_ESK5_osrEBCg
 [ledger] 2017-01-03T15:15:42.538Z ledger:koa info <-| GET /websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTY1NDIsImV4cCI6MTQ4NDA2MTM0MiwiaXNzIjoiaHR0cHM6Ly91c2QuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL3VzZC5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9pbnRlcmxlZGdlciJ9.s0XO6rNr22XjFQZrMPcyl2yB4eSfXH_ESK5_osrEBCg
 [ledger] 2017-01-03T15:15:42.593Z ledger:rpcHandler info new ws subscriber for interledger:*
 [connector] request ledger metadata https://usd.interledger.network/ledger
 [connector] 2017-01-03T15:15:42.605Z connector:route-broadcaster info adding peer 9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0 via ledger peer.32oKK.mmk.
 [ledger] 2017-01-03T15:15:42.614Z ledger:koa info <-- GET /
 [ledger] 2017-01-03T15:15:42.617Z ledger:koa info --> GET / 200 3ms 984B
 [connector] 2017-01-03T15:15:42.634Z connector:route-broadcaster info broadcasting 1 routes to peer.32oKK.mmk.9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0
 [connector] 1 calling sendMessage with [ { ledger: 'peer.32oKK.mmk.',
 [connector]     account: 'peer.32oKK.mmk.-VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM',
 [connector]     data: { method: 'broadcast_routes', data: [Object] } } ] and id ded4edd1-f416-41ff-85a3-6d6c73fb0c8a
 [connector] 2017-01-03T15:15:42.641Z connector:app info connector ready (republic attitude)
[api]   ilp-plugin-bells:factory connecting admin plugin +0ms
[api]   ilp-plugin-bells:plugin connecting to account https://usd.interledger.network/ledger/accounts/admin +6ms
[ledger] 2017-01-03T15:15:46.638Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-01-03T15:15:46.648Z ledger:koa info --> GET /accounts/admin 200 10ms 127B
[api]   ilp-plugin-bells:plugin request ledger metadata https://usd.interledger.network/ledger +69ms
[ledger] 2017-01-03T15:15:46.677Z ledger:koa info <-- GET /
[ledger] 2017-01-03T15:15:46.685Z ledger:koa info --> GET / 200 8ms 984B
[api]   ilp-plugin-bells:plugin using service urls: { transfer: 'https://usd.interledger.network/ledger/transfers/:id',
[api]   transfer_fulfillment: 'https://usd.interledger.network/ledger/transfers/:id/fulfillment',
[api]   transfer_rejection: 'https://usd.interledger.network/ledger/transfers/:id/rejection',
[api]   account: 'https://usd.interledger.network/ledger/accounts/:name',
[api]   auth_token: 'https://usd.interledger.network/ledger/auth_token',
[api]   websocket: 'wss://usd.interledger.network/ledger/websocket',
[api]   message: 'https://usd.interledger.network/ledger/messages' } +37ms
[ledger] 2017-01-03T15:15:46.722Z ledger:koa info <-- GET /auth_token
[ledger] 2017-01-03T15:15:46.740Z ledger:koa info --> GET /auth_token 200 18ms 285B
[ledger] 2017-01-03T15:15:46.778Z ledger:koa info <-| GET /websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTY1NDYsImV4cCI6MTQ4NDA2MTM0NiwiaXNzIjoiaHR0cHM6Ly91c2QuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL3VzZC5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9hZG1pbiJ9.53uHX3Zg7DUrnhDZ8ycgEaHLHpuKPewyDLTqlbhJK1A
[api]   ilp-plugin-bells:plugin ws connected to wss://usd.interledger.network/ledger/websocket?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0ODM0NTY1NDYsImV4cCI6MTQ4NDA2MTM0NiwiaXNzIjoiaHR0cHM6Ly91c2QuaW50ZXJsZWRnZXIubmV0d29yay9sZWRnZXIiLCJzdWIiOiJodHRwczovL3VzZC5pbnRlcmxlZGdlci5uZXR3b3JrL2xlZGdlci9hY2NvdW50cy9hZG1pbiJ9.53uHX3Zg7DUrnhDZ8ycgEaHLHpuKPewyDLTqlbhJK1A +100ms
[ledger] 2017-01-03T15:15:46.804Z ledger:rpcHandler info new ws subscriber for admin:*
[api]   ilp-plugin-bells:factory retrieving ledger metadata +21ms
[api]   ilp-plugin-bells:plugin request ledger metadata https://usd.interledger.network/ledger +2ms
[ledger] 2017-01-03T15:15:46.893Z ledger:koa info <-- GET /
[ledger] 2017-01-03T15:15:46.902Z ledger:koa info --> GET / 200 9ms 984B
[connector] 2017-01-03T15:15:47.641Z connector:route-broadcaster warn broadcasting routes to peer.32oKK.mmk.9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0 failed
```

it seems - Both of connectors are failed at broadcasting. btw, I notice that there is not single quote for the broker in the log. 

``` 
[connector] undefined: connecting to host `mqtt://broker.hivemq.com:1883`...
```

```
CONNECTOR_ENABLE=true
CONNECTOR_LEDGERS={"mm.mmk.interledger.":{"currency":"MMK","plugin":"ilp-plugin-bells","options":{"account":"https://mmk.interledger.network/ledger/accounts/interledger","username":"interledger","password":"......"}},"peer.32oKK.usd.":{"currency":"USD","plugin":"ilp-plugin-virtual","store":true,"options":{"name":"","secret":"......","peerPublicKey":"-VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM","prefix":"peer.32oKK.usd.","broker":"mqtt://broker.hivemq.com:1883","maxBalance":"10000000000","currency":"USD","info":{"currencyCode":"USD","currencySymbol":"$","precision":10,"scale":10,"connectors":[{"id":"-VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM","name":"-VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM","connector":"peer.32oKK.usd.-VTsihTjLe2N6eM2GPsyIJ2vhi2lguU2WlKVwCcbcEM"}]}}}}
CONNECTOR_BACKEND=ilp-connector-backend-yahoo
CONNECTOR_FX_SPREAD=0.0010
CONNECTOR_MAX_HOLD_TIME=100
CONNECTOR_AUTOLOAD_PEERS=true
CONNECTOR_PORT=4000
```



```
CONNECTOR_LEDGERS={"us.usd.interledger.":{"currency":"USD", "plugin":"ilp-plugin-bells", "options":{"account":"https://usd.interledger.network/ledger/accounts/interledger","username":"interledger","password":"......"}},"peer.32oKK.mmk.":{"currency":"MMK", "plugin":"ilp-plugin-virtual", "store":true,"options":{ "name":"","secret":"......","peerPublicKey":"9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0","prefix":"peer.32oKK.mmk.","broker":"mqtt://broker.hivemq.com:1883","maxBalance":"1000000000000","currency":"MMK","info":{"currencyCode":"MMK","currencySymbol":"MMK","precision":10,"scale":10,"connectors":[{"id":"9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0","name":"9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0","connector":"peer.32oKK.mmk.9n7mFn1dGE2e3hI9kjPxV9xyIyP0JThxLJNf65xHwj0"}]}}}}
```

**Comment by sharafian** [comment]
One of your trustlines is over mmk, and the other is over usd. This means the connector thinks they're two different trustlines. Because a trustline is a virtual ledger, it needs to have just one currency. If you make both sides use usd, it should work.

**Comment by Winthan** [comment]
I tried to use both for usd, but it doesn't work at all. 

```
[api]  connector:route-broadcaster warn broadcasting routes to peer.8wAVm.usd.3Sg4IRxO3GQwSUZtCYhaJMv3EMeJHoI_ilJB9DaSdDY failed
[api]  connector:route-broadcaster info broadcasting 1 routes to peer.8wAVm.usd.3Sg4IRxO3GQwSUZtCYhaJMv3EMeJHoI_ilJB9DaSdDY
[api]  connector:route-broadcaster warn broadcasting routes to peer.8wAVm.usd.3Sg4IRxO3GQwSUZtCYhaJMv3EMeJHoI_ilJB9DaSdDY failed
[api]  connector:route-broadcaster info broadcasting 1 routes to peer.8wAVm.usd.3Sg4IRxO3GQwSUZtCYhaJMv3EMeJHoI_ilJB9DaSdDY
[api]  connector:route-broadcaster warn broadcasting routes to peer.8wAVm.usd.3Sg4IRxO3GQwSUZtCYhaJMv3EMeJHoI_ilJB9DaSdDY failed
```

**Comment by Winthan** [comment]
I think, my connector is running after this updates.

https://github.com/interledgerjs/ilp-kit/commit/5fe0d91cfc96d60ebb272fafadf0b74894076eb1

**Comment by sharafian** [comment]
have they both got the prefix `peer.8wAVm.usd.`? How come it's no longer `peer.32oKK.usd.`?

**Comment by Winthan** [comment]
@sharafian  I installed the latest package, so new peer key was created. New one is come connected in API, but the connectors seems not working for some reasons.

**Comment by sharafian** [comment]
Did you re-run `npm run peer` on both ILP kits, with the new public key from the kit that you regenerated?

**Comment by vhpoet** [comment]
@Winthan the peer adding from the UI doesn't work yet, I'm working on it

**Comment by Winthan** [comment]
@sharafian @vhpoet  the connector is working fine now with the latest. 👍
