### ISSUE TITLE
DB_URI not properly initialized

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#166]
If `API_DB_URI` is set as environment variable (and not in `env.list`) the ilp kit sets `DB_URI` to the string literal `'undefined'`, instead of the value `undefined`. In consequence, the connector fails with a rather cryptic error message:
```
ilp-kit[wallet3.example] [api] .../interledgerjs/five-bells-integration-test/integration-test/node_modules/sequelize/lib/sequelize.js:132
ilp-kit[wallet3.example] [api]     options.dialect = urlParts.protocol.replace(/:$/, '');
ilp-kit[wallet3.example] [api]                                        ^
ilp-kit[wallet3.example] [api]
ilp-kit[wallet3.example] [api] TypeError: Cannot read property 'replace' of null
ilp-kit[wallet3.example] [api]     at DB.Sequelize (.../interledgerjs/five-bells-integration-test/integration-test/node_modules/sequelize/lib/sequelize.js:132:40)
ilp-kit[wallet3.example] [api]     at DB (.../interledgerjs/five-bells-integration-test/integration-test/node_modules/five-bells-shared/lib/db.js:35:7)
ilp-kit[wallet3.example] [api]     at new PluginStore (...interledgerjs/five-bells-integration-test/integration-test/node_modules/ilp-connector/src/lib/pluginStore.js:9:15)
ilp-kit[wallet3.example] [api]     at Object.keys.forEach (...interledgerjs/five-bells-integration-test/integration-test/node_modules/ilp-connector/src/lib/core.js:21:15)
ilp-kit[wallet3.example] [api]     at Array.forEach (native)
ilp-kit[wallet3.example] [api]     at module.exports (.../interledgerjs/five-bells-integration-test/integration-test/node_modules/ilp-connector/src/lib/core.js:13:41)
ilp-kit[wallet3.example] [api]     at createApp (.../interledgerjs/five-bells-integration-test/integration-test/node_modules/ilp-connector/src/app.js:107:12)
ilp-kit[wallet3.example] [api]     at Object.<anonymous> (.../interledgerjs/five-bells-integration-test/integration-test/node_modules/ilp-connector/src/index.js:4:19)
ilp-kit[wallet3.example] [api]     at Module._compile (module.js:570:32)
ilp-kit[wallet3.example] [api]     at Object.Module._extensions..js (module.js:579:10)
ilp-kit[wallet3.example] [api]     at Module.load (module.js:487:32)
ilp-kit[wallet3.example] [api]     at tryModuleLoad (module.js:446:12)
ilp-kit[wallet3.example] [api]     at Function.Module._load (module.js:438:3)
ilp-kit[wallet3.example] [api]     at Module.require (module.js:497:17)
ilp-kit[wallet3.example] [api]     at require (internal/module.js:20:19)
ilp-kit[wallet3.example] [api]     at Object.<anonymous> (.../interledgerjs/five-bells-integration-test/integration-test/node_modules/ilp-kit/api/src/lib/connector.js:5:
```

To mitigate the problem, `DB_URI` should be initialized identically no matter if `API_DB_URI` is set in `env.list` or as environment variable. Note that this might also apply to other variables.

**Comment by vhpoet** [comment]
@dappelt you don't need to specify `API_DB_URI`, use `DB_URI` instead. `API_DB_URI` and `LEDGER_DB_URI` will be generated based on that.

**Comment by dappelt** [comment]
Yes, I realized that using `DB_URI` is sufficient. However, `API_DB_URI` is still support for backwards compatibility and hence I opened this issue.
