### ISSUE TITLE
Removing a peer causes Peers page not to load

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-kit#194]
If I try reloading the Peers page after removing one peer, the page says "No Peers" and this error shows up in the API logs:

```
0|npm      | [api] 2017-02-07T09:06:48.825Z error-handler ERROR TypeError: Cannot read property 'getBalance' of null
0|npm      | [api]     at Conncetor.getPeer (.../ilp-kit/api/src/lib/connector.js:203:73)
0|npm      | [api]     at next (native)
0|npm      | [api]     at onFulfilled (.../ilp-kit/node_modules/co/index.js:65:19)
0|npm      | [api] 2017-02-07T09:06:48.827Z error-handler ERROR TypeError: Cannot read property 'getBalance' of null
0|npm      | [api]     at Conncetor.getPeer (.../ilp-kit/api/src/lib/connector.js:203:73)
0|npm      | [api]     at next (native)
0|npm      | [api]     at onFulfilled (.../ilp-kit/node_modules/co/index.js:65:19)
0|npm      | [api] 2017-02-07T09:06:48.827Z http INFO   xxx GET /peers 500 170ms -
0|npm      | [api]
0|npm      | [api]   InternalServerError: TypeError: Cannot read property 'getBalance' of null
0|npm      | [api]       at Object.throw (.../ilp-kit/node_modules/koa.io/node_modules/koa/lib/context.js:90:23)
0|npm      | [api]       at Object.handleError (.../ilp-kit/node_modules/five-bells-shared/middlewares/error-handler.js:18:19)
0|npm      | [api]       at throw (native)
0|npm      | [api]       at onRejected (.../ilp-kit/node_modules/koa.io/node_modules/koa/node_modules/co/index.js:81:24)
```

**Comment by vhpoet** [comment]
Does [this](https://github.com/interledgerjs/ilp-kit/commit/4aa9fbd51e219fb07488aa7f6a6a8a378b2d8636) fix it?

**Comment by emschwartz** [comment]
Yes
