### ISSUE TITLE
admin account cannot send payments

### ISSUE THREAD

**Issue by whotooktwarden** [interledgerjs/ilp-kit#214]
When I try to initiate a payment to my test account twarden for 1 BTC, I receive this error in the terminal

```
[ledger] 2017-02-13T04:23:34.326Z ledger:koa info <-- PUT /transfers/9473dc0e-b5c2-4e8a-8a10-5e792ee7183b
[ledger] 2017-02-13T04:23:34.442Z ledger:koa info --> PUT /transfers/9473dc0e-b5c2-4e8a-8a10-5e792ee7183b 201 116ms 744B
[ledger] 2017-02-13T04:23:34.493Z ledger:koa info <-- PUT /transfers/9473dc0e-b5c2-4e8a-8a10-5e792ee7183b/fulfillment
[ledger] 2017-02-13T04:23:34.521Z ledger:error-handler error { error: insert into "L_FULFILLMENTS" ("CONDITION_FULFILLMENT", "TRANSFER_ID") values ('cf:0:YrdUR_nEsJaD8slxZmxOC6Ch1WkwtVsdD5kwCDcF8io', 7) ON CONFLICT DO NOTHING - syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:188:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:548:20)
[ledger]   name: 'error',
[ledger]   length: 85,
[ledger]   severity: 'ERROR',
[ledger]   code: '42601',
[ledger]   detail: undefined,
[ledger]   hint: undefined,
[ledger]   position: '134',
[ledger]   internalPosition: undefined,
[ledger]   internalQuery: undefined,
[ledger]   where: undefined,
[ledger]   schema: undefined,
[ledger]   table: undefined,
[ledger]   column: undefined,
[ledger]   dataType: undefined,
[ledger]   constraint: undefined,
[ledger]   file: 'scan.l',
[ledger]   line: '1052',
[ledger]   routine: 'scanner_yyerror' }
[ledger] 2017-02-13T04:23:34.523Z ledger:error-handler error error: insert into "L_FULFILLMENTS" ("CONDITION_FULFILLMENT", "TRANSFER_ID") values ('cf:0:YrdUR_nEsJaD8slxZmxOC6Ch1WkwtVsdD5kwCDcF8io', 7) ON CONFLICT DO NOTHING - syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:188:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:548:20)
[ledger] 2017-02-13T04:23:34.524Z ledger:koa info xxx PUT /transfers/9473dc0e-b5c2-4e8a-8a10-5e792ee7183b/fulfillment 500 31ms -
[api] Error: Transfer expired, money returned
[api]     at Timeout.setTimeout (/home/twarden/ilp-kit/node_modules/ilp/src/lib/sender.js:174:20)
[api]     at ontimeout (timers.js:365:14)
[api]     at tryOnTimeout (timers.js:237:5)
[api]     at Timer.listOnTimeout (timers.js:207:5)
[api] 2017-02-13T04:23:44.331Z error-handler WARN Server error:
[api] 2017-02-13T04:23:44.338Z http INFO   --> PUT /payments/d1889804-fe46-44f1-b00a-ed9424b84835 500 10s -

```

**Comment by vhpoet** [comment]
@whotooktwarden what's your postgres version?

**Comment by whotooktwarden** [comment]
@vhpoet I installed postgres 6.9.3 as the setup recommended.

**Comment by vhpoet** [comment]
@whotooktwarden did you mistype the version? can't be 6.9.3.

**Comment by whotooktwarden** [comment]
@vhpoet I just checked, my prior comment was incorrect, it is version 9.3:

```
twarden@ilp-royalcrypto:~$ psql --version
psql (PostgreSQL) 9.3.15

```

**Comment by vhpoet** [comment]
@whotooktwarden and which doc recommends that version? That might be outdated. Can you try with that latest 9.6 ?

**Comment by whotooktwarden** [comment]
https://github.com/interledgerjs/ilp-kit/blob/master/docs/SETUP.md#server-setup mentions to use 9.3.

I installed version 9.6, psql --version says I am using 9.6.2.  Should I wipe the old database or then rerun npm run configure?

**Comment by vhpoet** [comment]
@whotooktwarden I don't see any mentions of 9.3 in the pointed doc. I guess it's just the default of the distribution. I would wipe the db just in case. No need to rerun configure, that should be fine.

@sharafian can we get the doc updated to say you need at least 9.5?

**Comment by whotooktwarden** [comment]
@vhpoet Alright, I wiped the database, setup another test user (twarden), and attempted to send 10 BTC from the admin and received the same error message.  It was truncated from the api line describing the quote, how do you access the logs so I can access the remainder of this error?
```

[api] 2017-02-13T20:26:46.263Z http INFO   --> POST /receivers/twarden 200 84ms -
[ledger] 2017-02-13T20:26:46.299Z ledger:koa info <-- PUT /transfers/dbeee844-ac96-4672-81ea-1fca306fb93b
[ledger] 2017-02-13T20:26:46.476Z ledger:koa info --> PUT /transfers/dbeee844-ac96-4672-81ea-1fca306fb93b 201 177ms 731B
[ledger] 2017-02-13T20:26:46.507Z ledger:koa info <-- PUT /transfers/dbeee844-ac96-4672-81ea-1fca306fb93b/fulfillment
[ledger] 2017-02-13T20:26:46.547Z ledger:error-handler error { error: insert into "L_FULFILLMENTS" ("CONDITION_FULFILLMENT", "TRANSFER_ID") values ('cf:0:_0oBN0n6iqqVqgnIg62oP0VSh3sOZkHlZSMMpP-pQ_s', 2) ON CONFLICT DO NOTHING - syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:188:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:548:20)
[ledger]   name: 'error',
[ledger]   length: 85,
[ledger]   severity: 'ERROR',
[ledger]   code: '42601',
[ledger]   detail: undefined,
[ledger]   hint: undefined,
[ledger]   position: '134',
[ledger]   internalPosition: undefined,
[ledger]   internalQuery: undefined,
[ledger]   where: undefined,
[ledger]   schema: undefined,
[ledger]   table: undefined,
[ledger]   column: undefined,
[ledger]   dataType: undefined,
[ledger]   constraint: undefined,
[ledger]   file: 'scan.l',
[ledger]   line: '1052',
[ledger]   routine: 'scanner_yyerror' }
[ledger] 2017-02-13T20:26:46.550Z ledger:error-handler error error: insert into "L_FULFILLMENTS" ("CONDITION_FULFILLMENT", "TRANSFER_ID") values ('cf:0:_0oBN0n6iqqVqgnIg62oP0VSh3sOZkHlZSMMpP-pQ_s', 2) ON CONFLICT DO NOTHING - syntax error at or near "ON"
[ledger]     at Connection.parseE (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:539:11)
[ledger]     at Connection.parseMessage (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:366:17)
[ledger]     at Socket.<anonymous> (/home/twarden/ilp-kit/node_modules/pg/lib/connection.js:105:22)
[ledger]     at emitOne (events.js:96:13)
[ledger]     at Socket.emit (events.js:188:7)
[ledger]     at readableAddChunk (_stream_readable.js:176:18)
[ledger]     at Socket.Readable.push (_stream_readable.js:134:10)
[ledger]     at TCP.onread (net.js:548:20)
[ledger] 2017-02-13T20:26:46.562Z ledger:koa info xxx PUT /transfers/dbeee844-ac96-4672-81ea-1fca306fb93b/fulfillment 500 54ms -

```

@sharafian I upgraded to postgres 9.6.2 via:

```
sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get install postgresql-9.6
```

**Comment by vhpoet** [comment]
@whotooktwarden can you confirm that `psql -V` returns `9.6` ?

**Comment by whotooktwarden** [comment]
@vhpoet It returns version 9.6.2:

```
twarden@ilp-royalcrypto:~/ilp-kit$ psql -V
psql (PostgreSQL) 9.6.2

```

**Comment by vhpoet** [comment]
@whotooktwarden that's very strange, I'm 90% confident this is a versioning thing. insert ON CONFLICT was [introduced in 9.5](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29). My guess is that you still have two postgres installations and the user that's running the service is using the old version.

**Comment by whotooktwarden** [comment]
@vhpoet You are correct, version 9.3 was installed alongside it.  I removed both instances with apt-get --purge remove postgresql\* and reinstalled version 9.6.2 with sudo apt-get install postgresql-9.6.

Fortunately my admin account now reports -1000 BTC and the connector hold 1000 BTC.  I believe that this issue can now be closed!  I will now check on Peering with someone.

http://imgur.com/a/YtNNM

**Comment by whotooktwarden** [comment]
Please note that I was working on a Ubuntu 14.04 VPS for my most recently posted issues and not on CentOS 7.
