### ISSUE TITLE
Running ILP Kit with pm2 does not work

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#312]
When following the [instructions](https://github.com/interledgerjs/ilp-kit/blob/master/docs/SETUP.md#ilp-kit-configuration) to start ILP kit with pm2, the startup fails. The error is:

```
3|web      | Error: Cannot find module 'redux/actions/auth'
3|web      |     at Function.Module._resolveFilename (module.js:469:15)
3|web      |     at Function._module2.default._resolveFilename (/home/dappelt/ilp-kit/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:423:34)
3|web      |     at Function.Module._load (module.js:417:25)
3|web      |     at Module.require (module.js:497:17)
3|web      |     at require (internal/module.js:20:19)
3|web      |     at Object.<anonymous> (/home/dappelt/ilp-kit/src/routes.js:3:1)
3|web      |     at Module._compile (module.js:570:32)
3|web      |     at Module.require._compile (/home/dappelt/ilp-kit/node_modules/webpack-isomorphic-tools/source/index.js:513:28)
3|web      |     at loader (/home/dappelt/ilp-kit/node_modules/babel-register/lib/node.js:144:5)
3|web      |     at require.extensions.(anonymous function) (/home/dappelt/ilp-kit/node_modules/babel-register/lib/node.js:154:7)
3|web      |     at Object._module2.default._extensions.(anonymous function) [as .js] (/home/dappelt/ilp-kit/node_modules/require-hacker/babel-transpiled-modules/require hacker.js:260:68)
3|web      |     at Module.load (module.js:487:32)
3|web      |     at tryModuleLoad (module.js:446:12)
3|web      |     at Function.Module._load (module.js:438:3)
3|web      |     at Module.require (module.js:497:17)
3|web      |     at require (internal/module.js:20:19)
```

**Comment by dappelt** [comment]
Changing `pm2.config.js` like this solved it:

```
...
    {
      name      : 'web',
      script    : './bin/server.js',
      env: {
        "NODE_PATH": "./src",
        "NODE_ENV": "production"
      }
    }
...
```
