### ISSUE TITLE
paying too much makes the other ilp-kit owe you that amount

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#322]
When attempting to pay too much, the receiving ilp-kit will error with:

```
connector.rpc() failed:  NotAcceptedError: adding amount (16010000000) to balance (-18289354) exceeds maximum (10000000000)
    at NotAcceptedError (/home/michiel/ilp-kit/node_modules/ilp-plugin-virtual/src/util/errors.js:24:5)
    at Balance.add (/home/michiel/ilp-kit/node_modules/ilp-plugin-virtual/src/model/balance.js:64:13)
```

And instead of its balance staying the same, it decreases its own balance with the amount of the refused transfer.

**Comment by michielbdejong** [comment]
This was fixed.
