### ISSUE TITLE
internal server error on https://ilp-kit.michielbdejong.com/api/users/admin/profilepic

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-kit#337]
```
9|api      |   InternalServerError: TypeError: Path must be a string. Received null
9|api      |       at Object.throw (/home/michiel/ilp-kit/node_modules/koa/lib/context.js:91:23)
9|api      |       at Object.handleError (/home/michiel/ilp-kit/node_modules/five-bells-shared/middlewares/error-handler.js:18:19)
9|api      |       at handleError.throw (<anonymous>)
9|api      |       at onRejected (/home/michiel/ilp-kit/node_modules/co/index.js:81:24)
9|api      |       at propagateAslWrapper (/home/michiel/.nvm/versions/node/v6.9.5/lib/node_modules/pm2/node_modules/async-listener/index.js:421:23)
9|api      |       at /home/michiel/.nvm/versions/node/v6.9.5/lib/node_modules/pm2/node_modules/async-listener/index.js:458:70

**Comment by michielbdejong** [comment]
It should instead serve a generic profile pic when the user didn't upload one

**Comment by michielbdejong** [comment]
this is not an issue when the user did upload their profile pic, so less bad than I thought. removing bug label.
