### ISSUE TITLE
pg-migrator is not found when starting with pm2

### ISSUE THREAD

**Issue by dappelt** [interledgerjs/ilp-kit#355]
Error is: 

```
2017-05-05T14:11:06.208Z ledger:app info syncing database
2017-05-05T14:11:06.235Z ledger:app info database sync aborted. Error was:  { Error: spawn pg-migrator ENOENT
    at exports._errnoException (util.js:1029:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn pg-migrator',
  path: 'pg-migrator',
  spawnargs: [ 'postgres://dappelt:p4ssw0rt@localhost/ilpkit' ] }
```

Steps to reproduce: Create a new postgres DB, edit `env.list` so that ILP kit uses the new DB, and run `pm2 start pm2.config.js`.

The problem is that pm2 does not add `node_modules` to `$PATH` and, hence, `pg-migrator` is not found. This has to be fixed in `pm2.config.js`.

**Comment by dappelt** [comment]
fixed in interledgerjs/five-bells-ledger#421
