### ISSUE TITLE
unexpected server response (404)

### ISSUE THREAD

**Issue by misnuge** [interledgerjs/ilp-kit#36]
[4] 2016-11-02T00:16:15.913Z sequelize DEBUG Executing (default): SELECT "id", "username", "account", "name", "email", "email_verified", "github_id", "profile_picture", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'mspark' LIMIT 1;
[1] [2016-11-02T00:16:15.927Z]  INFO: ledger/21225 on interledger:   <-- GET /accounts/mspark (req_id=c50c9a67-48b6-4d14-badb-a3007b3462d3, module=app, query={})
[1] [2016-11-02T00:16:15.944Z]  INFO: ledger/21225 on interledger:   --> GET /accounts/mspark 200 17ms (req_id=c50c9a67-48b6-4d14-badb-a3007b3462d3, module=app, duration=17, status=200)
[4] normal account
[1] [2016-11-02T00:16:15.960Z]  INFO: ledger/21225 on interledger:   <-- GET /accounts/mslee (req_id=c4b642de-d199-4f26-88ae-a8719e95cf5b, module=app, query={})
[1] [2016-11-02T00:16:15.965Z]  INFO: ledger/21225 on interledger:   --> GET /accounts/mslee 200 5ms (req_id=c4b642de-d199-4f26-88ae-a8719e95cf5b, module=app, duration=5, status=200)
[4] 2016-11-02T00:16:15.982Z http INFO   <-- GET /receivers/mslee
[4] 2016-11-02T00:16:15.986Z sequelize DEBUG Executing (default): SELECT "id", "username", "account", "name", "email", "email_verified", "github_id", "profile_picture", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'mslee' LIMIT 1;
[4] 2016-11-02T00:16:15.995Z http INFO   --> GET /receivers/mslee 200 13ms -
[4] 2016-11-02T00:16:15.997Z http INFO   --> GET /parse/destination?destination=mslee 200 97ms -
[4] 2016-11-02T00:16:23.416Z http INFO   <-- POST /payments/quote
[4] 2016-11-02T00:16:23.421Z sequelize DEBUG Executing (default): SELECT "id", "username", "account", "name", "email", "email_verified", "github_id", "profile_picture", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'mspark' LIMIT 1;
[1] [2016-11-02T00:16:23.442Z]  INFO: ledger/21225 on interledger:   <-- GET /accounts/mspark (req_id=cad9fb68-5776-4282-b7b9-8c179ce61c1f, module=app, query={})
[1] [2016-11-02T00:16:23.451Z]  INFO: ledger/21225 on interledger:   --> GET /accounts/mspark 200 9ms (req_id=cad9fb68-5776-4282-b7b9-8c179ce61c1f, module=app, duration=9, status=200)
[4] normal account
[1] [2016-11-02T00:16:23.463Z]  INFO: ledger/21225 on interledger:   <-- GET /accounts/mslee (req_id=ae5bd936-057d-48a4-91ed-d06d682cdb3f, module=app, query={})
[1] [2016-11-02T00:16:23.466Z]  INFO: ledger/21225 on interledger:   --> GET /accounts/mslee 200 3ms (req_id=ae5bd936-057d-48a4-91ed-d06d682cdb3f, module=app, duration=3, status=200)
[4] 2016-11-02T00:16:23.474Z http INFO   <-- GET /receivers/mslee
[4] 2016-11-02T00:16:23.476Z sequelize DEBUG Executing (default): SELECT "id", "username", "account", "name", "email", "email_verified", "github_id", "profile_picture", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'mslee' LIMIT 1;
[4] 2016-11-02T00:16:23.484Z http INFO   --> GET /receivers/mslee 200 10ms -
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp-kit:spsp created a sender object
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp-plugin-bells-admin:plugin connecting to account https://****.***/ledger/accounts/mspark
[1] [2016-11-02T00:16:23.503Z]  INFO: ledger/21225 on interledger:   <-- GET /accounts/mspark (req_id=c2f29cbc-c16a-488f-ad12-d89b5f0c6cee, module=app, query={})
[1] [2016-11-02T00:16:23.509Z]  INFO: ledger/21225 on interledger:   --> GET /accounts/mspark 200 6ms (req_id=c2f29cbc-c16a-488f-ad12-d89b5f0c6cee, module=app, duration=6, status=200)
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp-plugin-bells-admin:plugin request ledger metadata http://***.***:3000
[1] [2016-11-02T00:16:23.515Z]  INFO: ledger/21225 on interledger:   <-- GET / (req_id=0cb9b8d8-8daf-4e97-b5fa-3835354ec1bd, module=app, query={})
[1] [2016-11-02T00:16:23.518Z]  INFO: ledger/21225 on interledger:   --> GET / 200 3ms (req_id=0cb9b8d8-8daf-4e97-b5fa-3835354ec1bd, module=app, duration=3, status=200)
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp-plugin-bells-admin:plugin subscribing to wss://***.***/ledger/accounts/*/transfers
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp-plugin-bells-admin:plugin 'websocket: connected'
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp:sender got source amount quote response { sourceAmount: '1', destinationAmount: '1' }
[4] 2016-11-02T00:16:23.524Z http INFO   --> POST /payments/quote 200 109ms -
[1] [2016-11-02T00:16:23.528Z]  INFO: ledger/21225 on interledger:   <-- GET /accounts/*/transfers (req_id=5e912344-a377-4ff3-aac0-9b0b60c198b6, module=app, query={})
[1] [2016-11-02T00:16:23.535Z]  WARN: ledger/21225 on interledger:   --> GET /accounts/*/transfers 404 7ms (req_id=5e912344-a377-4ff3-aac0-9b0b60c198b6, module=app, duration=7, status=404)
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp-plugin-bells-admin:plugin 'websocket: error' [Error: unexpected server response (404)]
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp-plugin-bells-admin:plugin ws error on wss://***.***/ledger/accounts/*/transfers: Error: unexpected server response (404)
[4] Wed, 02 Nov 2016 00:16:23 GMT ilp-plugin-bells-admin:plugin 'websocket: disconnected'
[1] [2016-11-02T00:16:23.645Z]  INFO: ledger/21225 on interledger:   <-- GET /accounts/*/transfers (req_id=4e845565-daeb-4f5c-ae42-6550820c4459, module=app, query={})
[1] [2016-11-02T00:16:23.646Z]  WARN: ledger/21225 on interledger:   --> GET /accounts/*/transfers 404 1ms (req_id=4e845565-daeb-4f5c-ae42-6550820c4459, module=app, duration=1, status=404)
[4] [piping] can't execute file: /home/mspark/ilp-kit/bin/api.js
[4] [piping] error given was: Error: unexpected server response (404)
[4]     at ClientRequest.response (/home/mspark/ilp-kit/node_modules/ws/lib/WebSocket.js:719:15)
[4]     at ClientRequest.g (events.js:260:16)
[4]     at emitOne (events.js:77:13)
[4]     at ClientRequest.emit (events.js:169:7)
[4]     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:414:21)
[4]     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
[4]     at TLSSocket.socketOnData (_http_client.js:304:20)
[4]     at emitOne (events.js:77:13)
[4]     at TLSSocket.emit (events.js:169:7)
[4]     at readableAddChunk (_stream_readable.js:146:16)
[4]     at TLSSocket.Readable.push (_stream_readable.js:110:10)
[4]     at TLSWrap.onread (net.js:523:20)

I am testing ilp-kit on Ubuntu 16.04. I think I have set all the environments variables and apache2 proxy configuration correctly on separate two machines as the README.MD says.  The two machines cooperates well except the error above.

Many thanks,

misnuge

**Comment by vhpoet** [comment]
@misnuge we're aware of this, and working on it at the moment. Will let you know when a fix is pushed.

**Comment by vhpoet** [comment]
@misnuge this should be fixed, feel free to reopen the ticket if it's still happening.
