### ISSUE TITLE
Payments fail on v2.0

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#366]
[api] 2017-05-09T17:02:53.261Z connector:message-router info got heartbeat from: peer.fJbTC.usd.9.KRixgcBCBdyQln7IBYiopjuNO78QSFtXgOwP1sbsCSk   [0/1966]
[api] 2017-05-09T17:02:53.262Z http INFO   --> POST /peers/rpc?method=send_message&prefix=peer.fJbTC.usd.9. 200 2ms -
[api] 2017-05-09T17:02:58.593Z http INFO   <-- POST /payments/quote
[api] 2017-05-09T17:02:58.604Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "pro
file_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users"
AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-05-09T17:02:58.635Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-05-09T17:02:58.642Z ledger:koa info --> GET /accounts/admin 200 7ms 219B
[ledger] 2017-05-09T17:02:59.219Z ledger:koa info <-- POST /messages
[ledger] 2017-05-09T17:02:59.237Z ledger:koa info --> POST /messages 201 18ms 442B
[api] 2017-05-09T17:02:59.250Z connector:route-builder info creating quote sourceAddress=us.usd.grifiti.admin sourceAmount=1000000000 destinationAddress
=us.usd.nexus.stefan.VQBzAkcKbeIWfcksYYpmkaD-Z9mA8VCNw destinationAmount=null slippage=undefined
[api] 2017-05-09T17:02:59.389Z http INFO   <-- POST /peers/rpc?method=send_message&prefix=peer.wUalC.usd.9.
[api] 2017-05-09T17:02:59.393Z http INFO   --> POST /peers/rpc?method=send_message&prefix=peer.wUalC.usd.9. 200 4ms -
[ledger] 2017-05-09T17:02:59.445Z ledger:koa info <-- POST /messages
[ledger] 2017-05-09T17:02:59.452Z ledger:koa info --> POST /messages 201 7ms 591B
[api] 2017-05-09T17:02:59.464Z http INFO   --> POST /payments/quote 200 871ms -
[api] 2017-05-09T17:03:02.383Z http INFO   <-- PUT /payments/428ef159-eb92-4a7a-b5fe-15da7e5a7f29
[api] 2017-05-09T17:03:02.386Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "pro
file_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users"
AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-05-09T17:03:02.423Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-05-09T17:03:02.431Z ledger:koa info --> GET /accounts/admin 200 8ms 219B
[ledger] 2017-05-09T17:03:02.493Z ledger:koa info <-- PUT /transfers/a2459e36-5652-4870-a99d-243890162c7a
[ledger] 2017-05-09T17:03:02.574Z ledger:koa info --> PUT /transfers/a2459e36-5652-4870-a99d-243890162c7a 201 81ms 1.2KB
[api] 2017-05-09T17:03:02.586Z connector:route-builder info constructing destination transfer sourceLedger=us.usd.grifiti. sourceAmount=1000000000 ilpPa
cket=AYIBlAAAAAA7Tp38NXVzLnVzZC5uZXh1cy5zdGVmYW4uVlFCekFrY0tiZUlXZmNrc1lZcG1rYUQtWjltQThWQ053ggFSUFNLLzEuMApOb25jZTogQVFhQ1BUdkd1LW9CS0ZyQU9HLWNXdwpFbmN
yeXB0aW9uOiBhZXMtMjU2LWdjbSB3ZkFsQzYyTHhQYkxWckF3N1FnMk9RCgoegz8PIRfxHNwSuB1JsQK3ZPNdRLyUJWWfw8wPXVU7NjYmBXZggkGOHATLr8aO8RfPHRHUcS_pT1Lamb02kc3L7tg--H6
-ncGim2BYAVAhBz5lOC43-zeof1-XEEV15ZgdnsxIbOQlVSCHZLJ_XjcHeejyK6tGSkUXtawItJQg1vt8QBNyA3vpe-X87hxaUpyCa9LWG6DNLw7F3a3EJCPYkKsWByNW1XNaoGrhe9T1lFB72-3RGAL
ncQHz1ubDhv9MBR5XVY3_Z7nfYjYZUo4R6b8zuyyFxmotgn6pawpdqjvRYXc2SKVx_eAdDHrBcgwwR9AdGEepP11vTW0A
[api] (node:25338) DeprecationWarning: switch from the "account" field to the "to" and "from" fields!
[api] 2017-05-09T17:03:08.531Z http INFO   <-- POST /peers/rpc?method=expire_transfer&prefix=peer.wUalC.usd.9.
[api] 2017-05-09T17:03:08.533Z peers ERROR connector.rpc() failed:  TransferNotFoundError: no prepared transfer with id e253927a-fe06-4b0e-8130-456b5c49
bfe8 was found.
[api]     at TransferLog._getCachedTransferWithInfo (/home/pkrey/ilp-kit/node_modules/ilp-plugin-virtual/src/model/transferlog.js:185:13)
[api]     at TransferLog.get (/home/pkrey/ilp-kit/node_modules/ilp-plugin-virtual/src/model/transferlog.js:45:17)
[api]     at PluginVirtual._handleExpireTransfer (/home/pkrey/ilp-kit/node_modules/ilp-plugin-virtual/src/lib/plugin.js:387:38)
[api]     at _handleExpireTransfer.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at HttpRpc.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at HttpRpc.toPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:118:63)
[api]     at next (/home/pkrey/ilp-kit/node_modules/co/index.js:99:29)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:69:7)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at HttpRpc.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at HttpRpc.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at HttpRpc.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:29)
[api]     at rpc (/home/pkrey/ilp-kit/api/src/controllers/peers.js:181:33)
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
[api]     at next (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
[api]     at checkPeerAuth (/home/pkrey/ilp-kit/api/src/controllers/peers.js:51:13)
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
[api]     at next (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
[api]     at /home/pkrey/ilp-kit/node_modules/koa-router/lib/router.js:326:16
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
[api]     at /home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa-router/lib/router.js:331:31)
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa/node_modules/koa-compose/index.js:44:32)
[api]     at next (/home/pkrey/ilp-kit/node_modules/koa/node_modules/koa-compose/index.js:45:18)
[api]     at p.then.cont (/home/pkrey/ilp-kit/node_modules/koa-passport/lib/framework/koa.js:144:16)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)
[api] 2017-05-09T17:03:08.533Z http INFO   --> POST /peers/rpc?method=expire_transfer&prefix=peer.wUalC.usd.9. 200 2ms -
[api] 2017-05-09T17:03:08.614Z connector:subscriptions warn error processing notification: TypeError: Cannot convert undefined or null to object
[api] (node:25338) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 28): TypeError: Cannot convert undefined or null to obje
ct
[api] Error: transfer a2459e36-5652-4870-a99d-243890162c7a failed.
[api]     at FiveBellsLedger.cancel (/home/pkrey/ilp-kit/node_modules/ilp/src/lib/spsp.js:213:14)
[api]     at FiveBellsLedger.EventEmitter.emitAsync (/home/pkrey/ilp-kit/node_modules/eventemitter2/lib/eventemitter2.js:437:31)
[api]     at FiveBellsLedger._handleNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:695:26)
[api]     at _handleNotification.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at FiveBellsLedger.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at FiveBellsLedger.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at PluginFactory._routeNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/factory.js:115:43)
[api]     at _routeNotification.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at PluginFactory.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at PluginFactory.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at FiveBellsLedger.adminPlugin.on (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/factory.js:52:42)
[api]     at FiveBellsLedger.EventEmitter.emitAsync (/home/pkrey/ilp-kit/node_modules/eventemitter2/lib/eventemitter2.js:434:31)
[api]     at FiveBellsLedger._handleIncomingRpcMessage (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:683:18)
[api]     at _handleIncomingRpcMessage.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at FiveBellsLedger.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at FiveBellsLedger.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at WebSocket.ws.on (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:250:16)
[api]     at emitTwo (events.js:106:13)
[api]     at WebSocket.emit (events.js:192:7)
[api]     at Receiver.ontext (/home/pkrey/ilp-kit/node_modules/ws/lib/WebSocket.js:841:10)
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/Receiver.js:536:18
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/Receiver.js:368:7
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/PerMessageDeflate.js:249:5
[api]     at afterWrite (_stream_writable.js:383:3)
[api]     at onwrite (_stream_writable.js:374:7)
[api]     at afterTransform (_stream_transform.js:79:3)
[api]     at TransformState.afterTransform (_stream_transform.js:54:12)
[api]     at Zlib.callback (zlib.js:625:5)
[api] 2017-05-09T17:03:09.475Z error-handler WARN Server error:
[api] 2017-05-09T17:03:09.476Z http INFO   --> PUT /payments/428ef159-eb92-4a7a-b5fe-15da7e5a7f29 500 7,093ms -
[api] 2017-05-09T17:03:10.401Z http INFO   <-- POST /peers/rpc?method=send_message&prefix=peer.wUalC.usd.9.
[api] 2017-05-09T17:03:10.402Z connector:message-router info got heartbeat from: peer.wUalC.usd.9.1W78wTNgWniBxOGyzLSVFJ0HvyPbCTVy57ohGzyhwC8
[api] 2017-05-09T17:03:10.403Z http INFO   --> POST /peers/rpc?method=send_message&prefix=peer.wUalC.usd.9. 200 2ms -
![failed_payment](https://cloud.githubusercontent.com/assets/4540878/25862974/d01d9cdc-349e-11e7-8dbf-d7f15c93ee6e.jpeg)

**Comment by peterjkrey** [comment]
with an non-admin account

[api] 2017-05-09T18:51:32.107Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "pro
file_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users"
AS "User" WHERE "User"."username" = 'krey' LIMIT 1;
[ledger] 2017-05-09T18:51:32.127Z ledger:koa info <-- GET /accounts/krey
[ledger] 2017-05-09T18:51:32.133Z ledger:koa info --> GET /accounts/krey 200 6ms 192B
[ledger] 2017-05-09T18:51:32.208Z ledger:koa info <-- GET /accounts/krey
[ledger] 2017-05-09T18:51:32.215Z ledger:koa info --> GET /accounts/krey 200 7ms 192B
[ledger] 2017-05-09T18:51:32.231Z ledger:rpcHandler info new ws subscriber for krey:*
[ledger] 2017-05-09T18:51:33.029Z ledger:koa info <-- POST /messages
[ledger] 2017-05-09T18:51:33.040Z ledger:koa info --> POST /messages 201 11ms 440B
[api] 2017-05-09T18:51:33.061Z connector:route-builder info creating quote sourceAddress=us.usd.grifiti.krey sourceAmount=1000000000 destinationAddress=
us.usd.nexus.stefan.VQBzAkcKbeIh64DZqIEpB8sVSJJ8uEkZA destinationAmount=null slippage=undefined
[api] 2017-05-09T18:51:33.639Z http INFO   <-- POST /peers/rpc?method=send_message&prefix=peer.wUalC.usd.9.
[api] 2017-05-09T18:51:33.643Z http INFO   --> POST /peers/rpc?method=send_message&prefix=peer.wUalC.usd.9. 200 4ms -
[ledger] 2017-05-09T18:51:33.695Z ledger:koa info <-- POST /messages
[ledger] 2017-05-09T18:51:33.700Z ledger:koa info --> POST /messages 201 5ms 590B
[api] 2017-05-09T18:51:33.718Z http INFO   --> POST /payments/quote 200 1,615ms -
[api] 2017-05-09T18:51:34.724Z http INFO   <-- PUT /payments/d5b1347a-aff1-4075-88de-7f510fd2f20c
[api] 2017-05-09T18:51:34.726Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "pro
file_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users"
AS "User" WHERE "User"."username" = 'krey' LIMIT 1;
[ledger] 2017-05-09T18:51:34.742Z ledger:koa info <-- GET /accounts/krey
[ledger] 2017-05-09T18:51:34.750Z ledger:koa info --> GET /accounts/krey 200 8ms 192B
[ledger] 2017-05-09T18:51:34.813Z ledger:koa info <-- PUT /transfers/f1052356-3a55-4dd2-879a-10fc401c18e8
[ledger] 2017-05-09T18:51:34.915Z ledger:koa info --> PUT /transfers/f1052356-3a55-4dd2-879a-10fc401c18e8 201 102ms 1.2KB
[api] 2017-05-09T18:51:34.937Z connector:route-builder info constructing destination transfer sourceLedger=us.usd.grifiti. sourceAmount=1000000000 ilpPa
cket=AYIBqwAAAAA7Tp38NXVzLnVzZC5uZXh1cy5zdGVmYW4uVlFCekFrY0tiZUloNjREWnFJRXBCOHNWU0pKOHVFa1pBggFpUFNLLzEuMApOb25jZTogR3c3cnFBVUx4QW12UXpMcUc2Rnl0UQpFbmN
yeXB0aW9uOiBhZXMtMjU2LWdjbSBDSlNQR2hac0FNeXF2TUdyWjZXc0RBCgrEffCGFG7Y92JTgvtt_z_gL3xCAbejIgQ0TH-AJNbKlJQCye_gB3FJidOlN2o29TIF33yD127gfn8XfVCB-15adEPBh6P
vofKQ4F7Ump8y-zPYXSqDYtcxXqK9XhXBjvunP41Nr79x88vD0sykj2rabEXg23Z1OhVqtpvcW-21dE6x8GVG19dmiKpN0tPAhfXeVbiQj1KrBJFx_oWoUW1p9vs_eo3UVq9-jqudvb-UMyui6yW8Bfk
s4F30ik3F6O-7Qnc2E5-ozh3KMHMDFDkM6R1nRwMcaTqLEcTrvA33Gz-rxwHBghjdFBO2jfJ83TqDW4EHcVKjpZwD645a5c3AA9E9ejxIbuka4fjFThPQWUTs1AA
[api] (node:20606) DeprecationWarning: switch from the "account" field to the "to" and "from" fields!
[api] 2017-05-09T18:51:40.854Z http INFO   <-- POST /peers/rpc?method=expire_transfer&prefix=peer.wUalC.usd.9.
[api] 2017-05-09T18:51:40.857Z peers ERROR connector.rpc() failed:  TransferNotFoundError: no prepared transfer with id 1353d1bc-b756-4df0-86f9-7091e12e
c9cf was found.
[api]     at TransferLog._getCachedTransferWithInfo (/home/pkrey/ilp-kit/node_modules/ilp-plugin-virtual/src/model/transferlog.js:185:13)
[api]     at TransferLog.get (/home/pkrey/ilp-kit/node_modules/ilp-plugin-virtual/src/model/transferlog.js:45:17)
[api]     at PluginVirtual._handleExpireTransfer (/home/pkrey/ilp-kit/node_modules/ilp-plugin-virtual/src/lib/plugin.js:387:38)
[api]     at _handleExpireTransfer.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at HttpRpc.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at HttpRpc.toPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:118:63)
[api]     at next (/home/pkrey/ilp-kit/node_modules/co/index.js:99:29)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:69:7)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at HttpRpc.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at HttpRpc.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at HttpRpc.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:29)
[api]     at rpc (/home/pkrey/ilp-kit/api/src/controllers/peers.js:181:33)
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
[api]     at next (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
[api]     at checkPeerAuth (/home/pkrey/ilp-kit/api/src/controllers/peers.js:51:13)
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
[api]     at next (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
[api]     at /home/pkrey/ilp-kit/node_modules/koa-router/lib/router.js:326:16
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
[api]     at /home/pkrey/ilp-kit/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa-router/lib/router.js:331:31)
[api]     at dispatch (/home/pkrey/ilp-kit/node_modules/koa/node_modules/koa-compose/index.js:44:32)
[api]     at next (/home/pkrey/ilp-kit/node_modules/koa/node_modules/koa-compose/index.js:45:18)
[api]     at p.then.cont (/home/pkrey/ilp-kit/node_modules/koa-passport/lib/framework/koa.js:144:16)
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)
[api] 2017-05-09T18:51:40.857Z http INFO   --> POST /peers/rpc?method=expire_transfer&prefix=peer.wUalC.usd.9. 200 3ms -
[api] 2017-05-09T18:51:40.920Z connector:subscriptions warn error processing notification: TypeError: Cannot convert undefined or null to object
[api] (node:20606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): TypeError: Cannot convert undefined or null to obje
ct
[api] (node:20606) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminat
e the Node.js process with a non-zero exit code.
[api] Error: transfer f1052356-3a55-4dd2-879a-10fc401c18e8 failed.
[api]     at FiveBellsLedger.cancel (/home/pkrey/ilp-kit/node_modules/ilp/src/lib/spsp.js:213:14)
[api]     at FiveBellsLedger.EventEmitter.emitAsync (/home/pkrey/ilp-kit/node_modules/eventemitter2/lib/eventemitter2.js:437:31)
[api]     at FiveBellsLedger._handleNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:695:26)
[api]     at _handleNotification.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at FiveBellsLedger.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at FiveBellsLedger.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at PluginFactory._routeNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/factory.js:115:43)
[api]     at _routeNotification.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at PluginFactory.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at PluginFactory.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at FiveBellsLedger.adminPlugin.on (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/factory.js:52:42)
[api]     at FiveBellsLedger.EventEmitter.emitAsync (/home/pkrey/ilp-kit/node_modules/eventemitter2/lib/eventemitter2.js:434:31)
[api]     at FiveBellsLedger._handleIncomingRpcMessage (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:683:18)
[api]     at _handleIncomingRpcMessage.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at FiveBellsLedger.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at FiveBellsLedger.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at WebSocket.ws.on (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:250:16)
[api]     at emitTwo (events.js:106:13)
[api]     at WebSocket.emit (events.js:192:7)
[api]     at Receiver.ontext (/home/pkrey/ilp-kit/node_modules/ws/lib/WebSocket.js:841:10)
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/Receiver.js:536:18
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/Receiver.js:368:7
[api]     at /home/pkrey/ilp-kit/node_modules/ws/lib/PerMessageDeflate.js:249:5
[api]     at afterWrite (_stream_writable.js:383:3)
[api]     at onwrite (_stream_writable.js:374:7)
[api]     at afterTransform (_stream_transform.js:79:3)
[api]     at TransformState.afterTransform (_stream_transform.js:54:12)
[api]     at Zlib.callback (zlib.js:625:5)
[api] 2017-05-09T18:51:41.810Z error-handler WARN Server error:
[api] 2017-05-09T18:51:41.811Z http INFO   --> PUT /payments/d5b134

**Comment by peterjkrey** [comment]
@vhpoet @justmoon  This issue was fixed by sending funds from the admin account to the connector account.
