### ISSUE TITLE
Payments are failing

### ISSUE THREAD

**Issue by peterjkrey** [interledgerjs/ilp-kit#392]
[api] 2017-05-15T15:25:53.041Z connector:route-broadcaster info detectedDown! account: peer.AZV7p.usd.9.Sk0gGc3mz9_Ci2eLTTBPfuMdgFEW3hRj0QTRvWFZBEQ lostLedgerLinks: []      [0/1973]
[api] 2017-05-15T15:25:53.041Z connector:route-broadcaster warn broadcasting routes to peer.AZV7p.usd.9.Sk0gGc3mz9_Ci2eLTTBPfuMdgFEW3hRj0QTRvWFZBEQ failed
[api] 2017-05-15T15:25:53.218Z connector:route-broadcaster info detectedDown! account: peer.tY3pV.usd.9.Y_luxphkAy6ddYzuXb9lXxS60zg5tHjrPh8zz_BfwEA lostLedgerLinks: []
[api] 2017-05-15T15:25:53.219Z connector:route-broadcaster warn broadcasting routes to peer.tY3pV.usd.9.Y_luxphkAy6ddYzuXb9lXxS60zg5tHjrPh8zz_BfwEA failed
[api] 2017-05-15T15:25:53.220Z http INFO   <-- GET /webfinger/?resource=acct:krey@grifiti.web-payments.net
[ledger] 2017-05-15T15:25:53.222Z ledger:koa info <-- GET /accounts/krey
[ledger] 2017-05-15T15:25:53.229Z ledger:koa info --> GET /accounts/krey 200 7ms 195B
[api] 2017-05-15T15:25:53.230Z http INFO   --> GET /webfinger/?resource=acct:krey@grifiti.web-payments.net 200 10ms -
[api] 2017-05-15T15:25:53.239Z connector:route-broadcaster info detectedDown! account: peer.nCPbg.usd.9.MrH7ZQqiu48JEHjqE_BsE-PaMxUs8yvR0VSA8I8ZwQ8 lostLedgerLinks: []
[api] 2017-05-15T15:25:53.239Z connector:route-broadcaster warn broadcasting routes to peer.nCPbg.usd.9.MrH7ZQqiu48JEHjqE_BsE-PaMxUs8yvR0VSA8I8ZwQ8 failed
[api] 2017-05-15T15:25:53.352Z http INFO   <-- GET /spsp/krey
[api] 2017-05-15T15:25:53.355Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "destination", "profile_picture", "name", "phone
", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at", "invite_code" FROM "Users" AS "User" WHERE "User"."username" = 'krey' LIMIT 1;
[api] 2017-05-15T15:25:53.357Z ledger INFO getting ledger info http://localhost:3101
[ledger] 2017-05-15T15:25:53.358Z ledger:koa info <-- GET /
[ledger] 2017-05-15T15:25:53.360Z ledger:koa info --> GET / 200 2ms 1013B
[api] 2017-05-15T15:25:53.360Z http INFO   --> GET /spsp/krey 200 8ms -
[api] 2017-05-15T15:25:53.583Z http INFO   <-- POST /peers/rpc?method=send_message&prefix=peer.L203-.usd.9.
[api] 2017-05-15T15:25:53.584Z connector:route-builder info creating quote sourceAddress=peer.L203-.usd.9.lpNd7n6iAOWTHVLvG0GxrVC1xuGTjnyQA5cHlqg01gI sourceAmount=99800000 destinati
onAddress=us.usd.grifiti.krey.1P23_XoThaU5-a86xVzR1oF6x4EXqakvQ destinationAmount=undefined slippage=0
[api] 2017-05-15T15:25:53.585Z http INFO   --> POST /peers/rpc?method=send_message&prefix=peer.L203-.usd.9. 200 2ms -
[api] Error: transfer 57e0c943-b240-4a26-a6aa-92f8745f0e19 failed.
[api]     at FiveBellsLedger.cancel (/home/pkrey/ilp-kit/node_modules/ilp/src/lib/spsp.js:226:14)
[api]     at FiveBellsLedger.EventEmitter.emitAsync (/home/pkrey/ilp-kit/node_modules/eventemitter2/lib/eventemitter2.js:437:31)
[api]     at FiveBellsLedger._handleNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/plugin.js:695:26)
[api]     at _handleNotification.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at FiveBellsLedger.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at FiveBellsLedger.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at PluginFactory._routeNotification (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/factory.js:115:43)
[api]     at _routeNotification.next (<anonymous>)
[api]     at onFulfilled (/home/pkrey/ilp-kit/node_modules/co/index.js:65:19)
[api]     at /home/pkrey/ilp-kit/node_modules/co/index.js:54:5
[api]     at PluginFactory.co (/home/pkrey/ilp-kit/node_modules/co/index.js:50:10)
[api]     at PluginFactory.createPromise (/home/pkrey/ilp-kit/node_modules/co/index.js:30:15)
[api]     at FiveBellsLedger.adminPlugin.on (/home/pkrey/ilp-kit/node_modules/ilp-plugin-bells/src/lib/factory.js:52:42)
[api]     at FiveBellsLedger.EventEmitter.emitAsync (/home/pkrey/ilp-kit/node_modules/eventemitter2/lib/eventemitter2.js:434:31)
[api] 2017-05-15T15:25:53.782Z error-handler WARN Server error:
[api] 2017-05-15T15:25:53.782Z http INFO   --> PUT /payments/ec728de3-2a4a-462a-b7df-4ba294a843d4 500 7,074ms -

**Comment by peterjkrey** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/4540878/26065325/62c5b256-3948-11e7-816c-45d5d28fc26a.jpeg)

**Comment by peterjkrey** [comment]
Appears that receiver gets the payment but shows failed on sender.
