### ISSUE TITLE
through2

### ISSUE THREAD

**Issue by elmurci** [interledgerjs/ilp-kit#69]
```
[api] Executing script: start-dev-api
[api] 
[api] to be executed: node ./bin/api.js 
[connector] 
[connector] npm run start-dev-connector exited with code 0
[ledger] module.js:471
[ledger]     throw err;
[ledger]     ^
[ledger] 
[ledger] Error: Cannot find module 'through2'
[ledger]     at Function.Module._resolveFilename (module.js:469:15)
[ledger]     at Function.Module._load (module.js:417:25)
[ledger]     at Module.require (module.js:497:17)
[ledger]     at require (internal/module.js:20:19)

**Comment by vhpoet** [comment]
This is probably due to an npm network issue. The ledger has the `through2` dependency specified in the [package](https://github.com/interledgerjs/five-bells-ledger/blob/master/package.json#L90). Please reopen if this happens on every install.

**Comment by elmurci** [comment]
hey, my fault.
As it was a dev dependency had to run `npm install dev`
